### ISSUE TITLE
Remove hard coded Postgres password in chart

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-tractusx/managed-identity-wallet#40]
At the time of writing the Postgres password is hard coded. This is not necessary, as postgres is able to generate a random password.

From values.yaml

```yaml

# @ignored
postgresql:
  primary:
    initdb:
      scripts:
        init_db_script.sh: |
          #!/bin/sh
          createdb -O postgres miw
      user: postgres
      password: postgres
  auth:
    password: postgres
    username: postgres
    postgresPassword: postgres
```
